### PR TITLE
order send email fix

### PR DESCRIPTION
**Pull request by praveenavennakula**
let me know your comments

### CODE REVIEW

**Comment by haigopi** [comment]
Did you run the test? Can you post the test results?

**Comment by praveenavennakula** [comment]
kickofftestsresult
ovrallfeature_result

**Comment by praveenavennakula** [comment]
let me know if u need any more details.

**Comment by praveenavennakula** [comment]
[Order_Send_email_failed_doc_ref.docx](https://github.com/haigopi/VantaShala-Tests/files/1790869/Order_Send_email_failed_doc_ref.docx)

**Comment by praveenavennakula** [comment]
just created a document for my reference.you can see this for more details.

**Comment by praveenavennakula** [comment]
I found this as temporary solution to the issue.Now i found some other fix for this issue. so closing this pull request.

**Pull request closed without merging**
